[package]
name = "fp-web-patcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "fp_web_patcher"
path = "src/bin/bin.rs"

[dependencies]
adler32 = "1.2.0"
wasm-bindgen = "0.2.87"
